name: uni_chat
description: "A powerful AI agent client"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  http: ^1.5.0
  flutter_markdown: ^0.7.7+1
  file_picker: ^10.3.1
  uuid: ^4.5.1
  flutter_math_fork: ^0.7.4
  flutter_code_editor: ^0.3.4
  highlight: ^0.7.0
  langchain: ^0.7.9
  langchain_openai: ^0.7.6
  langchain_google: ^0.6.5+2
  gpt_markdown: ^1.1.2
  shimmer_animation: ^2.2.2
  super_drag_and_drop: ^0.9.1
  flutter_staggered_grid_view: ^0.7.0
  fl_chart: any
  webview_flutter: ^4.13.0
  clipboard: ^2.0.2
  whiteboard: ^1.0.0
  dio: ^5.9.0
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  overlay_dialog: ^0.2.2
  macos_window_utils: ^1.9.0
  local_hero: ^0.3.0
  device_info_plus: ^11.5.0
  shared_preferences: ^2.5.3
  objectbox: ^5.0.0
  docx_to_text: ^1.0.1
  langchain_community: ^0.2.0+1
  xxh3: ^1.2.0
  jieba_flutter: ^0.2.0
  objectbox_flutter_libs: any
  bitsdojo_window: ^0.1.6
  sqflite_common_ffi: ^2.3.6
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0
  build_runner: ^2.7.1
  objectbox_generator: any

flutter:

  uses-material-design: true
  shaders:
    - lib/Shaders/grid.frag
  # To add assets to your application, add an assets section, like this:
  # 哪个傻逼想出来用yaml来当配置文件的，是用json会死吗？还是toml不符合你心意？
  #tmd这个assets真的是弱智，要不然找不到这个，要不然找不到那个。放进去了找不到，我甚至都不知道他到底是真的放进去了还是压根没有索引到
  # 还得考虑是不是老子空格写多了弱智玩意识别错误
  assets:
    - resources/
    - resources/provider_model_icons/
flutter_intl:
  enabled: true
