// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;

import 'RAG/rag_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 8001683930286863590),
    name: 'VectorQueryObject1024',
    lastPropertyId: const obx_int.IdUid(4, 8641084489542781430),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7937841496436511238),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5329314641450822060),
        name: 'chunkId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8641084489542781430),
        name: 'embedding',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(5, 4059720193560210819),
        hnswParams: obx_int.ModelHnswParams(dimensions: 1024, distanceType: 2),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 4516592352703106748),
    name: 'VectorQueryObject1536',
    lastPropertyId: const obx_int.IdUid(4, 265275311139452338),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7800007715475430260),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2987906692772672927),
        name: 'chunkId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 265275311139452338),
        name: 'embedding',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(6, 191570679810021719),
        hnswParams: obx_int.ModelHnswParams(dimensions: 1536, distanceType: 2),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 6082567141989829605),
    name: 'VectorQueryObject384',
    lastPropertyId: const obx_int.IdUid(4, 1020703042506374568),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5436179558352414741),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 3740269702890355911),
        name: 'chunkId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1020703042506374568),
        name: 'embedding',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(7, 3709718771155285881),
        hnswParams: obx_int.ModelHnswParams(dimensions: 384, distanceType: 2),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 1644127769993034001),
    name: 'VectorQueryObject768',
    lastPropertyId: const obx_int.IdUid(4, 3174077998503644527),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1288904205378451365),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2820715848253976210),
        name: 'chunkId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3174077998503644527),
        name: 'embedding',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(8, 2092130301566339729),
        hnswParams: obx_int.ModelHnswParams(dimensions: 768, distanceType: 2),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
obx.Store openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) {
  return obx.Store(
    getObjectBoxModel(),
    directory: directory,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(4, 1644127769993034001),
    lastIndexId: const obx_int.IdUid(8, 2092130301566339729),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [
      5350696812232343158,
      1920171254633875237,
      8489971654036426380,
      1480161122123000580,
    ],
    retiredPropertyUids: const [
      4247944410172469336,
      4819405260127586611,
      3427678450927411164,
      6481424380038309076,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    VectorQueryObject1024: obx_int.EntityDefinition<VectorQueryObject1024>(
      model: _entities[0],
      toOneRelations: (VectorQueryObject1024 object) => [],
      toManyRelations: (VectorQueryObject1024 object) => {},
      getId: (VectorQueryObject1024 object) => object.id,
      setId: (VectorQueryObject1024 object, int id) {
        object.id = id;
      },
      objectToFB: (VectorQueryObject1024 object, fb.Builder fbb) {
        final chunkIdOffset = fbb.writeString(object.chunkId);
        final embeddingOffset = fbb.writeListFloat32(object.embedding);
        fbb.startTable(5);
        fbb.addInt64(0, object.id ?? 0);
        fbb.addOffset(2, chunkIdOffset);
        fbb.addOffset(3, embeddingOffset);
        fbb.finish(fbb.endTable());
        return object.id ?? 0;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          4,
        );
        final chunkIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final embeddingParam = const fb.ListReader<double>(
          fb.Float32Reader(),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 10, []);
        final object = VectorQueryObject1024(
          id: idParam,
          chunkId: chunkIdParam,
          embedding: embeddingParam,
        );

        return object;
      },
    ),
    VectorQueryObject1536: obx_int.EntityDefinition<VectorQueryObject1536>(
      model: _entities[1],
      toOneRelations: (VectorQueryObject1536 object) => [],
      toManyRelations: (VectorQueryObject1536 object) => {},
      getId: (VectorQueryObject1536 object) => object.id,
      setId: (VectorQueryObject1536 object, int id) {
        object.id = id;
      },
      objectToFB: (VectorQueryObject1536 object, fb.Builder fbb) {
        final chunkIdOffset = fbb.writeString(object.chunkId);
        final embeddingOffset = fbb.writeListFloat32(object.embedding);
        fbb.startTable(5);
        fbb.addInt64(0, object.id ?? 0);
        fbb.addOffset(2, chunkIdOffset);
        fbb.addOffset(3, embeddingOffset);
        fbb.finish(fbb.endTable());
        return object.id ?? 0;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          4,
        );
        final chunkIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final embeddingParam = const fb.ListReader<double>(
          fb.Float32Reader(),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 10, []);
        final object = VectorQueryObject1536(
          id: idParam,
          chunkId: chunkIdParam,
          embedding: embeddingParam,
        );

        return object;
      },
    ),
    VectorQueryObject384: obx_int.EntityDefinition<VectorQueryObject384>(
      model: _entities[2],
      toOneRelations: (VectorQueryObject384 object) => [],
      toManyRelations: (VectorQueryObject384 object) => {},
      getId: (VectorQueryObject384 object) => object.id,
      setId: (VectorQueryObject384 object, int id) {
        object.id = id;
      },
      objectToFB: (VectorQueryObject384 object, fb.Builder fbb) {
        final chunkIdOffset = fbb.writeString(object.chunkId);
        final embeddingOffset = fbb.writeListFloat32(object.embedding);
        fbb.startTable(5);
        fbb.addInt64(0, object.id ?? 0);
        fbb.addOffset(2, chunkIdOffset);
        fbb.addOffset(3, embeddingOffset);
        fbb.finish(fbb.endTable());
        return object.id ?? 0;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          4,
        );
        final chunkIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final embeddingParam = const fb.ListReader<double>(
          fb.Float32Reader(),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 10, []);
        final object = VectorQueryObject384(
          id: idParam,
          chunkId: chunkIdParam,
          embedding: embeddingParam,
        );

        return object;
      },
    ),
    VectorQueryObject768: obx_int.EntityDefinition<VectorQueryObject768>(
      model: _entities[3],
      toOneRelations: (VectorQueryObject768 object) => [],
      toManyRelations: (VectorQueryObject768 object) => {},
      getId: (VectorQueryObject768 object) => object.id,
      setId: (VectorQueryObject768 object, int id) {
        object.id = id;
      },
      objectToFB: (VectorQueryObject768 object, fb.Builder fbb) {
        final chunkIdOffset = fbb.writeString(object.chunkId);
        final embeddingOffset = fbb.writeListFloat32(object.embedding);
        fbb.startTable(5);
        fbb.addInt64(0, object.id ?? 0);
        fbb.addOffset(2, chunkIdOffset);
        fbb.addOffset(3, embeddingOffset);
        fbb.finish(fbb.endTable());
        return object.id ?? 0;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          4,
        );
        final chunkIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final embeddingParam = const fb.ListReader<double>(
          fb.Float32Reader(),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 10, []);
        final object = VectorQueryObject768(
          id: idParam,
          chunkId: chunkIdParam,
          embedding: embeddingParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [VectorQueryObject1024] entity fields to define ObjectBox queries.
class VectorQueryObject1024_ {
  /// See [VectorQueryObject1024.id].
  static final id = obx.QueryIntegerProperty<VectorQueryObject1024>(
    _entities[0].properties[0],
  );

  /// See [VectorQueryObject1024.chunkId].
  static final chunkId = obx.QueryStringProperty<VectorQueryObject1024>(
    _entities[0].properties[1],
  );

  /// See [VectorQueryObject1024.embedding].
  static final embedding = obx.QueryHnswProperty<VectorQueryObject1024>(
    _entities[0].properties[2],
  );
}

/// [VectorQueryObject1536] entity fields to define ObjectBox queries.
class VectorQueryObject1536_ {
  /// See [VectorQueryObject1536.id].
  static final id = obx.QueryIntegerProperty<VectorQueryObject1536>(
    _entities[1].properties[0],
  );

  /// See [VectorQueryObject1536.chunkId].
  static final chunkId = obx.QueryStringProperty<VectorQueryObject1536>(
    _entities[1].properties[1],
  );

  /// See [VectorQueryObject1536.embedding].
  static final embedding = obx.QueryHnswProperty<VectorQueryObject1536>(
    _entities[1].properties[2],
  );
}

/// [VectorQueryObject384] entity fields to define ObjectBox queries.
class VectorQueryObject384_ {
  /// See [VectorQueryObject384.id].
  static final id = obx.QueryIntegerProperty<VectorQueryObject384>(
    _entities[2].properties[0],
  );

  /// See [VectorQueryObject384.chunkId].
  static final chunkId = obx.QueryStringProperty<VectorQueryObject384>(
    _entities[2].properties[1],
  );

  /// See [VectorQueryObject384.embedding].
  static final embedding = obx.QueryHnswProperty<VectorQueryObject384>(
    _entities[2].properties[2],
  );
}

/// [VectorQueryObject768] entity fields to define ObjectBox queries.
class VectorQueryObject768_ {
  /// See [VectorQueryObject768.id].
  static final id = obx.QueryIntegerProperty<VectorQueryObject768>(
    _entities[3].properties[0],
  );

  /// See [VectorQueryObject768.chunkId].
  static final chunkId = obx.QueryStringProperty<VectorQueryObject768>(
    _entities[3].properties[1],
  );

  /// See [VectorQueryObject768.embedding].
  static final embedding = obx.QueryHnswProperty<VectorQueryObject768>(
    _entities[3].properties[2],
  );
}
