import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

The sidebars can be generated from the filesystem, or explicitly defined here.

Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    'intro', // 对应 docs/Intro.md
    {
      type: 'category',
      label: 'QuickStart',
      items: [
        {
          type: 'autogenerated',
          dirName: 'QuickStart',
        },
      ],
    },
    {
      type: 'category',
      label: 'API Providers',
      link: { type: 'generated-index', slug: '/category/api-providers' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'API Providers',
        },
      ],
    },
    {
      type: 'category',
      label: 'Agents',
      link: {
        type: 'generated-index', // Docusaurus v2/v3 的推荐做法
        title: 'Agents Overview',
        slug: '/category/agents',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'Agents', // 自动找到 docs/Agents/ 里面的所有 .md 文件
        },
      ],
    },
    {
      type: 'category',
      label: 'KnowledgeBases',
      link: { type: 'generated-index', slug: '/category/knowledgebases' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'KnowledgeBases',
        },
      ],
    },
    {
      type: 'category',
      label: 'Personas',
      link: { type: 'generated-index', slug: '/category/personas' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'Personas',
        },
      ],
    },

  ],
};

export default sidebars;
