import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // 简化为全自动生成，依靠目录结构和 _category_.json 控制
  tutorialSidebar: [
    'intro',
    {
      type: 'autogenerated',
      dirName: '.', // 扫描所有文档
    },
  ],
};

export default sidebars;
